version: '3.5'
services:
  blog.users.mongo:
    image: mongo
    restart: always
    container_name: blog.users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: blog-users

    ports:
      - 27017:27017

    volumes:
      - blog.mongo.users:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/blog-users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  blog.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: blog.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@blog.users.mongo:27017/

volumes:
  blog.mongo.users:
